# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: First job
    steps:
    - bash: echo Build First job
  - job: Second job
    steps:
    - bash: echo Build Second job

- stage: dev
  jobs:
  - job: dev job
    steps:
    - bash: echo Build Dev job
- stage: test
  jobs:
  - job: test job
    steps:
    - bash: echo Build test job
- stage: production
  jobs:
  - job: production job
    steps:
    - bash: echo Build production job

steps:
- script: echo job1 step1!
  displayName: 'Run a one-line script'
