# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps:
    - bash: echo Build First job
  - job: Secondjob
    steps:
    - bash: echo Build Second job

- stage: dev
  dependsOn: Build
  jobs:
  - job: devjob
    steps:
    - bash: echo Build Dev job
- stage: test
  dependsOn: Build
  jobs:
  - job: testjob
    steps:
    - bash: echo Build test job
- stage: production
  dependsOn:
  - dev
  - test
  jobs:
  - job: productionjob
    steps:
    - bash: echo Build production job
